# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            unrouted.io
tagline:          'Just sume stuff'
description:      'Stuff. Lots of computer stuff.'
url:              http://unrouted.io

author:
  name:           'John Carr'
  url:            https://twitter.com/Jc2k

paginate:         5
