# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            unrouted.io
tagline:          'Just some stuff'
description:      'Stuff. Lots of computer stuff.'
url:              http://unrouted.io

author:
  name:           'John Carr'
  url:            https://github.com/Jc2k

paginate:         5

gems:
  - jemoji
